.TH leveleditor 7
.SH NAME
leveleditor \-A level creator and editor for infinte tux
.SH SYNOPSIS
.B infinte tux level editor
.TP
.SH DESCRIPTION
.B infinte tux level editor
A level creator and editor for infinte tux
.SH OPTIONS
.TP
f  Full screen mode
Example:

leveleditor f
.SH DISCLAIMER
use at your own risk.
.SH AUTHORS 

