#!/bin/bash
if [ -d "leveleditor" ]; then
    rm -rf leveleditor
fi

if [ -d "dist" ]; then
    rm -rf dist
fi   

mkdir leveleditor
mkdir dist

javac -source 1.7 -target 1.7 -d \
./leveleditor ./src/main/java/com/mojang/mario/*.java \
./src/main/java/com/mojang/mario/level/*.java \
./src/main/java/com/mojang/mario/mapedit/*.java \
./src/main/java/com/mojang/mario/sprites/*.java \
./src/main/java/com/mojang/sonar/*.java \
./src/main/java/com/mojang/sonar/mixer/*.java \
./src/main/java/com/mojang/sonar/sample/*.java

cp -R ./src/main/resources/* ./leveleditor
cp copyright_bsd_3_clause.txt ./leveleditor
cp copyright ./leveleditor

jar cfm leveleditor.jar manifest.txt -C ./leveleditor .
mv leveleditor.jar ./dist
#rm -rf leveleditor

echo "#!/bin/bash" > ./dist/leveleditor
echo 'MAINCLASS="com.mojang.mario.mapedit.NewLevelEditor"' >> ./dist/leveleditor
echo 'OPTION=$1"s"' >> ./dist/leveleditor
echo 'if [ "$OPTION" == "fs" ]; then' >> ./dist/leveleditor
echo     'MAINCLASS="com.mojang.mario.mapedit.NewLevelEditor"' >> ./dist/leveleditor
echo 'fi' >> ./dist/leveleditor
echo 'java -cp .:leveleditor.jar $MAINCLASS' >> ./dist/leveleditor
chmod +x ./dist/leveleditor
chmod +x ./dist/leveleditor.jar





